import Head from "next/head";
import Link from "next/link";

export default function Main() {
  return (
    <>
      <Head>
        <title>Sistema de control de vuelos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Link href="/login">Login</Link>
      </main>
    </>
  );
}
