import Head from "next/head";
import { useContext } from "react";
import HomeNavigation from "../../components/home/HomeNavigation";
import { Context } from "../../store/context";

import classes from "../../styles/Styles.module.css";

export default function Home() {
  const fullName = useContext(Context).user?.fullName;

  return (
    <div>
      <Head>
        <title>Sistema de control de vuelos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={classes.header}>
        <h1>Bienvenido {fullName}</h1>
      </header>
      <HomeNavigation />
    </div>
  );
}
